# -*- coding: utf-8 -*-

import unittest
import json
from base.web_Login_Getcookie import Login
import requests
import json
import random
import time
from base.sqlserver_connection import SqlServer_connectin
from base.get_st_stock_quantity import Get_st_stock_quantity
import datetime
from base.host_header import Host
from base.get_orderNo import Get_OrderNo
from requests_toolbelt import MultipartEncoder
from urllib3 import encode_multipart_formdata
from base.my_log import  MyLog
from base.read_config import ReadConfig
from base import get_project_path
from base.get_cookie import Get_cookie
import datetime
import xmltodict
import re

class Run_send(unittest.TestCase):
    """获取类Get_OrderNo里的初始化数值变量，用反射所有流程单号就一致，跑不下去"""
    mylog = MyLog()
    i = random.randint(0, 9999)
    get_orderNo = Get_OrderNo(i,"客服销售单到erp生产流程")
    date = get_orderNo.date
    date_time = get_orderNo.date_time
    date3 = get_orderNo.date3  # 当前日期+3
    d_date = get_orderNo.d_date
    current_milli_time_13 = get_orderNo.current_milli_time_13
    date1 = get_orderNo.date1
    scorder_No= get_orderNo.scorderNo
    mylog.info("{0}的单号是：{1}".format("销售生产组装生产单", scorder_No))
    @classmethod
    def setUpClass(cls):
        cls.mylog.info("客服销售单到erp生产流程开始\n")

    def setUp(self):
        self.session = requests.session()
        self.get_st_stock_quantity = Get_st_stock_quantity()

        """获取配置文件erp、报价系统主机地址、头部信息.存货等"""
        conf_path = get_project_path.config_path
        self.customersys_host= eval(ReadConfig.get_config(get_project_path.config_path,"Customer_Sys","customersys"))['host']
        self.customersys_login_header = eval(ReadConfig.get_config(get_project_path.config_path,"Customer_Sys","customersys"))['login_header']
        self.erp_header_formdata = eval(ReadConfig.get_config(get_project_path.config_path, "ERP", "erp"))['header_formdata']
        self.erp_host = eval(ReadConfig.get_config(get_project_path.config_path, "ERP", "erp"))['host']
        self.erp_login_header = eval(ReadConfig.get_config(get_project_path.config_path, "ERP", "erp"))['login_header']
        self.erp_header = eval(ReadConfig.get_config(get_project_path.config_path, "ERP", "erp"))['header']
        self.CustomerSys_customercode = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['customercode']
        self.CustomerSys_customerName = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['customerName']
        self.CustomerSys_product_code = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['product_code']
        self.CustomerSys_product_name = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['product_name']
        self.shipConfirmSave_header = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['shipConfirmSave_header']
        self.saleCount = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['saleCount']
        self.unit = eval(ReadConfig.get_config(get_project_path.config_path, "Customer_Sys", "customersys"))['unit']
        self.get_cookie = Get_cookie()
        self.SqlServer = SqlServer_connectin()
    # def write_report(self):
    #     report_path = "D:\\pycharm_project\\requsts_inference\\report\\report.html"
    #     fp = open(report_path, 'wb')
    #     suit = unittest.TestSuite()
    #     suit.addTest(self.test1())
    #     suit.addTest(self.test2())
    #     # case_list = ('test1','test2')
    #     # suit.addTests(case_list)
    #     # unittest.TextTestRunner().run(suit)
    #     runner = HTMLTestRunner.HTMLTestRunner(stream=fp, title='接口测试报告', description="这是接口测试报告")
    #     runner.run(suit)

    def test01(self):
        self.mylog.info('这是第一个测试用例:客服系统新增销售单')
        login_requert_data = {"account": "admin",
                             "userPwd": "xmsx123"}
        cookies=self.get_cookie.customer_sys_get_cookies(self.session,self.customersys_host,login_requert_data,self.customersys_login_header)
        url1="/customer/order/saveOrder.do"
        #with open(r"C:\Users\Administrator\Desktop\ERP.doc", mode="rb") as f:
        file = {
        #"breserve": ("ERP.doc", f.read()),  # 引号的file是接口的字段，后面的是文件的名称、文件的内容
        "breserve": ("", ""),  # 不上传附件
        "search_modelmodule": "",
        "customer_customercode":"FF6251200019412D",
        "receiveCheck":"产成品F3827",
        "projectname":"lyj项目20211025",
        "subindustry":"lyj行业20211025",
        "contemplate":0,
        "newcustomer":0,
        "contractnature":"销售",
        "customercode":"FF6251200019412D",
        "customertype":0,
        "technicalmanager":"严永金",
        "branchname":"四信通信",
        "depart":9,
        "audit":2,
        "departmanager":"张绍炜-部门经理",
        "invoicesituate":"专票",
        "name":"林云",
        "sutyparagraph":"123",
        "address":"厦门市集美区孙坂南路86~88号 88-1 南楼2楼仓库（务必送货上楼，禁止放置快递柜）；厦门四信电子技术有限公司；收件人：杨尚志；电话：0592-6021827、15934715030",
        "openbank":"12313131231",
        "depositsituation":"无",
        "depositsite":"",
        "skillname":1,
        "paymentmethod":"款到发货",
        "estpaymentdate":"2021-10-25",
        "guaranteescale":1,
        "cooptype":1,
        "presupport":"陈海燕,谢海海,",
        "prodUser":"曾润芳",
        "loanperiod":"",
        "contractnotes":"合同无特殊要求",
        "businessnotes":"",
        "business"	:"付焰波",
        "contractUser":"魏琴",
        "invoicrequire":"无开票要求",
        "invoUser":"黄梨蓉",
        "shipexchangedesc":"无财务备注",
        "recipientaddr":"同收货地址",
        "deliverynotes":"北大青鸟（JB-TB-JBF-11S）,数据上四信平台，再推送到智赣119平台",
        "oldbreserve":"",
        "tipflag":"",
        "countProduct":1,
        #"breserve"	:"",
        "contact":"test",
        "contactid":"",
        "mobilephone":"13799865324",
        "email":"",
        "fixedphone":"",
        "idBundle":"f260ee9c154e45849c9cf7b1aad30c97",
        "products_num":2,
        "moduleid_1":"",
        "typecode_1":"",
        "modelmodule_1":"5.CP.3630-LoRa模块",
        "signsname_1":"",
        "softversion_1":"",
        "quantity_1":self.saleCount,
        "unitprice_1":220,
        "warrantycard_1":self.saleCount,
        "accessories_1":"标配+北大青鸟 （JB-TB-JBF-11S)",
        "packages_1":"单独",
        "hardwarecustom_1"	:"无",
        "softwarecustom_1":"无",
        "customparts_1":"无",
        "customsigns_1":"无",
        "breserve_1":"5001070007-L51",
        "pname_1":"5.CP.3630-LoRa模块",
        "software_1":"",
        "warranty_1":365,
        "fixedtype_1":"不固定",
        "prodrequired_1":"",
        "unit_1":"台",
        "ids":"f260ee9c154e45849c9cf7b1aad30c97,"
        }
        encode_data = encode_multipart_formdata(file)
        file_data = encode_data[0]
        # print(file_data)
        self.erp_header_formdata["Content-Type"] = encode_data[1]
        result1 = self.session.post(self.customersys_host+url1, data=file_data, headers=self.erp_header_formdata,verify=False,cookies=cookies)
        #self.assertEqual(json.loads(result1.text)['msg'], "succ", msg="接口请求失败")
        self.assertTrue(json.loads(result1.text)['success'], msg="接口请求失败")  #json.loads(result1.text)['success']获取到True为布尔值
        self.mylog.info(result1.text)  #str
        #self.mylog.info(type(json.loads(result1.text)["success"]))   #bool：Ture

    def test02(self):
        self.mylog.info('这是第二个测试用例:ERP技术确认')
        self.mylog.info('——先查询sale_tech_confirm获取信息——')
        cookies = self.get_cookie.get_cookie(self.session, self.erp_host, self.erp_login_header, "xiehaihai", "xiehaihai")
        sql = """SELECT TOP 1 *  FROM sale_order a
                JOIN  sale_tech_confirm  b ON a.order_no = b.order_no
                WHERE a.custom_code = '{0}'
                order by a.id  desc""".format(self.CustomerSys_customercode) #查询客户的id最大（最新）销售单
        global saleorder_No,detailId,techCode,sale_tech_confirm_id
        saleorder_No= self.SqlServer.query_one_data(sql)[2]
        self.mylog.info('客服的销售单号是：{0}'.format(saleorder_No))
        createTime =self.SqlServer.query_one_data(sql)[4].strftime('%Y-%m-%d %H:%M:%S') #查询出来<class 'datetime.datetime'>，json不支持转换
        print(createTime)
        print(createTime)
        techCode = self.SqlServer.query_one_data(sql)[14]
        detailId = self.SqlServer.query_one_data(sql)[13]
        sale_tech_confirm_id = self.SqlServer.query_one_data(sql)[12]
        current_time=time.strftime('%Y%m%d%H%M%S ', time.localtime(time.time()))
        #print(current_time)
        url2 = "/sale/saleorder/saveTCInfoTeBom"
        request_data2 = {
        "saleOrderEntity": {
        "softProductLine": "",
        "createTime": createTime,
        "customCode": self.CustomerSys_customercode,
        "orderNo": saleorder_No,
        "sales": "付焰波",
        "review": None,
        "nature": "销售",
        "demand": None,
        "exchange": "无财务备注",
        "techCode": techCode,
        "standard": "4",
        "companyName": "厦门四信通信科技有限公司",
        "customerName": self.CustomerSys_customerName,
        "company": 3
    },
        "saleTechConfirmEntity": {
        "stockCode": self.CustomerSys_product_code,
        "id": sale_tech_confirm_id,
        "stockModel": "5.CP.3630-LoRa模块",
        "pack": "单独",
        "warrantycard": str(self.saleCount),
        "saleCount": self.saleCount,
        "signs": "无",
        "softVersion": "",
        "softVersionMade": "无",
        "hardwareMade": "无",
        "parts": "标配+北大青鸟 （JB-TB-JBF-11S)",
        "partsMade": "无",
        "remark": "",
        "detailId": detailId,
        "techCode":techCode,
        "bom": 12944,
        "bomId": 12944,
        "bomVersion": "V1.0.0.1",
        "tempAttr": 1,
        "tempName": self.CustomerSys_product_name+"-"+current_time,
        "tempMark": "",
        "confirmStatus": 1
    },
        "saleTechBillEntityList": [
        {
            "category": "20整机配件-选配",
            "id": 9616,
            "stockCode": "3701020000-76S",
            "oldStockCode": "",
            "productName": "1.WK.0033-1.WK.0033-天线帽",
            "stockCount": 1690,
            "outStoreId": "",
            "remark": "",
            "supplierCode": "",
            "supplierName": "",
            "bitNo": "",
            "bitNoS": "",
            "weld": "",
            "statusType": "自定义",
            "stockModel": "天线帽",
            "buyWay": 1320,
            "stockEnableCount": -47032,
            "groupName": "370102 孔塞",
            "status": 4,
            "stockCode1": "3701020000",
            "needQuantity": "1"
        },
        {
            "id": 177648,
            "bomId": 12944,
            "category": "10主机-选配",
            "partName": None,
            "status": 0,
            "statusName": None,
            "stockId": None,
            "stockCode": "2005020014-7GS",
            "oldStockCode": None,
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "1.EZ.0391-直插排针",
            "stockModel": None,
            "bomModel": "4PI单排直插插针,间距2.54MM,针长11.6mm",
            "stockVirtual": 0,
            "replaceStocks": "2005020014-7GS",
            "purchaseQuantity": None,
            "subBomId": 177640,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "义信盈科技",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": self.CustomerSys_product_code,
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 568,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 8134,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 8134,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 7566,
            "groupName": "200502 插件单排排针",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": 1,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "2005020014",
            "needCount1": 1,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 1,
            "needQuantity": 1
        },
        {
            "id": 177649,
            "bomId": 12944,
            "category": "10主机-选配",
            "partName": None,
            "status": 3,
            "statusName": None,
            "stockId": 16637,
            "stockCode": "3001070034-7AR",
            "oldStockCode": "2.YZ.0808",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "2.YZ.0808-半成品",
            "stockModel": None,
            "bomModel": "半成品F8L10A-H V1.1(样机)",
            "stockVirtual": 0,
            "replaceStocks": "3001070034-7AR",
            "purchaseQuantity": None,
            "subBomId": 177641,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "ZZZ",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": "2",
            "outStoreCode": "02",
            "outStoreName": "半成品仓",
            "remark": None,
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 365,
            "primaryStoreCode": "02",
            "primaryStoreName": "半成品仓",
            "stockCount": 20,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 20,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": -345,
            "groupName": "300107 LoRa模组和终端系列半成品",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": 1,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 600,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3001070034",
            "needCount1": 1,
            "replaceStockCode": "3001070034-7AR",
            "replaceStockId": 16637,
            "mStatus": 0,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 2,
            "needQuantity": 1
        },
        {
            "id": 177650,
            "bomId": 12944,
            "category": "20整机配件",
            "partName": None,
            "status": 0,
            "statusName": None,
            "stockId": None,
            "stockCode": "2003020010-7EH",
            "oldStockCode": None,
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "1.EZ.0194-直插插座",
            "stockModel": None,
            "bomModel": "5PIN单排直插插座,间距2.54MM",
            "stockVirtual": 0,
            "replaceStocks": "2003020010-7EH",
            "purchaseQuantity": None,
            "subBomId": 177642,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "金利翔",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 1579,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 6834,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 6834,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 5255,
            "groupName": "200302 插件WAFER",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": 1,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "2003020010",
            "needCount1": 1,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 3,
            "needQuantity": 1
        },
        {
            "id": 177651,
            "bomId": 12944,
            "category": "20整机配件-选配",
            "partName": None,
            "status": 3,
            "statusName": None,
            "stockId": 10588,
            "stockCode": "3903010233-7BP",
            "oldStockCode": "4.BP.1231",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "4.BP.1224-标牌",
            "stockModel": None,
            "bomModel": "F8L10A-H标牌(海外版:868/915MHz),耐高温PI材质,11.4*12.4mm",
            "stockVirtual": 0,
            "replaceStocks": "3903010235-7BP,3903010233-74V,3903010235-74V,3903010235-74V",
            "purchaseQuantity": None,
            "subBomId": 177643,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "维科电子",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 394,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 45159,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 50024,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 62909.953,
            "groupName": "390301 标准标牌",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": None,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3903010233",
            "needCount1": 1,
            "replaceStockCode": "3903010235-74V",
            "replaceStockId": 10588,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 4,
            "needQuantity": 1
        },
        {
            "id": None,
            "bomId": None,
            "category": "30包材",
            "partName": None,
            "status": 3,
            "statusName": None,
            "stockId": 33783,
            "stockCode": "4901070000-7AR",
            "oldStockCode": None,
            "newStockCodes": None,
            "disabled": None,
            "stockName": "单独包装虚拟件",
            "stockModel": None,
            "bomModel": "15个以下标准单独包装287*187*78mm（4.BC.0002+4.BC.0004）",
            "stockVirtual": None,
            "replaceStocks": "4901070001-7AR,4901070004-7AR,4901070005-7AR,4901070000-7AR,4901070000-7AR",
            "purchaseQuantity": None,
            "subBomId": 2446,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": None,
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": None,
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": None,
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": None,
            "buyWaitIn": None,
            "produceWaitOut": None,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": None,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": None,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": None,
            "stockEnableCount": None,
            "groupName": None,
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": "V1.0.1",
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": None,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": None,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": None,
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "4901070000",
            "needCount1": 1,
            "replaceStockCode": "4901070000-7AR",
            "replaceStockId": 33783,
            "expanded": True,
            "state": "open",
            "isLeaf": False,
            "level": 0,
            "seqindex": 5,
            "needQuantity": 1
        },
        {
            "id": 141504,
            "bomId": 2446,
            "category": "30 包材",
            "partName": None,
            "status": 2,
            "statusName": None,
            "stockId": 9914,
            "stockCode": "3901010001-74M",
            "oldStockCode": "4.BC.0002",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "4.BC.0002-4.BC.0002-4.BC.0002-纸盒",
            "stockModel": None,
            "bomModel": "标准MODEM/单口路由纸盒（28.7*18.7*7.8）",
            "stockVirtual": 0,
            "replaceStocks": "3901010001-73L",
            "purchaseQuantity": None,
            "subBomId": 141504,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "鸣人",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 2,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": None,
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": None,
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 500,
            "produceWaitOut": 41468.594,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 12229.2,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 322,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": -28739.395,
            "groupName": "390101 纸盒",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 2446,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": None,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "否",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3901010001",
            "needCount1": 2,
            "_parentId": 2446,
            "state": "open",
            "isLeaf": True,
            "level": 1,
            "seqindex": 6,
            "needQuantity": 2
        },
        {
            "id": 141505,
            "bomId": 2446,
            "category": "30 包材",
            "partName": None,
            "status": 2,
            "statusName": None,
            "stockId": 10031,
            "stockCode": "3902010000-7D2",
            "oldStockCode": "4.BC.0004",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "4.BC.0004-4.BC.0004-珍珠棉",
            "stockModel": None,
            "bomModel": "标准MODEM/单口路由珍珠棉（26.5*17.5*6.0）",
            "stockVirtual": 0,
            "replaceStocks": "3902010000-7CT,3902010000-73T",
            "purchaseQuantity": None,
            "subBomId": 141505,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "日月兴",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": None,
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": None,
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 1427.926,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 26078.062,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 424.93,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 24650.137,
            "groupName": "390201 珍珠棉",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 2446,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": None,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "否",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3902010000",
            "needCount1": 1,
            "_parentId": 2446,
            "state": "open",
            "isLeaf": True,
            "level": 1,
            "seqindex": 7,
            "needQuantity": 1
        },
        {
            "id": 177655,
            "bomId": 12944,
            "category": "30包材-选配",
            "partName": None,
            "status": 1,
            "statusName": None,
            "stockId": 28622,
            "stockCode": "3301020027-70Z",
            "oldStockCode": "3.WY.0165",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "3.WY.0165-LoRa吸盘单极子天线",
            "stockModel": None,
            "bomModel": "1m长,频率410-510MHz,接头SMA-J,线材 RG174,尺寸 143mm",
            "stockVirtual": 0,
            "replaceStocks": "3301020027-76S,3301020027-70Z",
            "purchaseQuantity": None,
            "subBomId": 177645,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "仕研",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 156,
            "primaryStoreCode": "01",
            "primaryStoreName": "材料仓",
            "stockCount": 4777,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 4777,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 4621,
            "groupName": "330102 吸盘天线",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": None,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3301020027",
            "needCount1": 1,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 8,
            "needQuantity": 1
        },
        {
            "id": 177656,
            "bomId": 12944,
            "category": "30包材-选配",
            "partName": None,
            "status": 1,
            "statusName": None,
            "stockId": 28624,
            "stockCode": "3301020028-70Z",
            "oldStockCode": "3.WY.0166",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "3.WY.0166-蜂窝吸盘单极子天线",
            "stockModel": None,
            "bomModel": "1m长,频率848-935MHz,接头SMA-J,线材 RG174,尺寸 90mm",
            "stockVirtual": 0,
            "replaceStocks": "3301020028-76L,3301020028-76S,3301020028-70Z",
            "purchaseQuantity": None,
            "subBomId": 177646,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "仕研",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 1,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": None,
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 371,
            "primaryStoreCode": "01",
            "primaryStoreName": "材料仓",
            "stockCount": 4789,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 4789,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 4418,
            "groupName": "330102 吸盘天线",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": 1,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3301020028",
            "needCount1": 1,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 9,
            "needQuantity": 1
        },
        {
            "id": 177657,
            "bomId": 12944,
            "category": "30包材-选配",
            "partName": None,
            "status": 1,
            "statusName": None,
            "stockId": 10185,
            "stockCode": "3902070006-71H",
            "oldStockCode": "4.BC.0165",
            "newStockCodes": None,
            "disabled": 1,
            "stockName": "4.BC.0165-4.BC.0165-载带",
            "stockModel": None,
            "bomModel": "F8L10A载带,φ330mm,宽度24.5mm,每格15*15mm,1000PCS/卷(临时)",
            "stockVirtual": 0,
            "replaceStocks": "3902070006-71H",
            "purchaseQuantity": None,
            "subBomId": 177647,
            "unitId": None,
            "unitValue": "PCS",
            "brandName": "精力通",
            "bitNo": None,
            "bitNoS": None,
            "needCount": 0.001,
            "lossRate": 0,
            "outStoreId": None,
            "outStoreCode": None,
            "outStoreName": None,
            "remark": "根据需要选配",
            "parentStockId": None,
            "parentStockCode": "5001070007-L51",
            "parentStockName": None,
            "parentStockModel": None,
            "parentStockColor": None,
            "bomVersion": "V1.0.0.1",
            "weld": None,
            "stockPicture": None,
            "subBomValue": None,
            "productCount": None,
            "convertRate": None,
            "secondUnitValue": None,
            "secondNeedCount": None,
            "cost": None,
            "machineCost": None,
            "purchaseWaitIn": 0,
            "buyWaitIn": 0,
            "produceWaitOut": 1.056,
            "primaryStoreCode": None,
            "primaryStoreName": None,
            "stockCount": 5009.575,
            "storeStockCount": None,
            "companyStockCount": None,
            "allStockCount": 5009.575,
            "allStockEnableCount": None,
            "relstock": None,
            "importNum": None,
            "stockReplaceEntityList": None,
            "children": None,
            "stockDefaultStoreEntities": None,
            "buyWay": 0,
            "stockEnableCount": 5008.519,
            "groupName": "390207 其他（打包带、拉伸膜、栈板、干燥剂）",
            "selfmade": None,
            "sell": None,
            "consume": None,
            "labour": None,
            "virtual": None,
            "outsourcing": None,
            "replaceOrder": None,
            "subParentId": 0,
            "subVersion": None,
            "subVersionDesc": None,
            "subUpdateDesc": None,
            "subAuditDesc": None,
            "bomType": None,
            "bomStatus": None,
            "expandReplace": 1,
            "exportDesc": None,
            "takeQuantity": None,
            "stockCodeBrand": None,
            "lowPrice": None,
            "taxRate": None,
            "priceType": None,
            "supplierCode": None,
            "supplierName": None,
            "currency": None,
            "turnoverDay": None,
            "productWaitIn": 0,
            "productCode": None,
            "productName": None,
            "productModel": None,
            "isCruxStock": "是",
            "priceTotal": None,
            "standardPrice": None,
            "needQuantityYear": None,
            "price": None,
            "stockCode1": "3902070006",
            "needCount1": 0.001,
            "expanded": True,
            "state": "open",
            "isLeaf": True,
            "level": 0,
            "seqindex": 10,
            "needQuantity": 0.001
        }
    ]
}
        result2 = self.session.post(self.erp_host+ url2,data=json.dumps(request_data2),headers=self.erp_header,cookies=cookies,verify=False)
        self.assertEqual(result2.json()["msg"], "success", msg="接口请求失败")
        self.mylog.info(result2.text)

    def test03(self):
        self.mylog.info('这是第三个测试用例:客服系统制作合同下单')
        login_requert_data = {"account": "admin",
                             "userPwd": "xmsx123"}
        cookies=self.get_cookie.customer_sys_get_cookies(self.session,self.customersys_host,login_requert_data,self.customersys_login_header)
        url1="/customer/contract/shipConfirmSave.do"
        request_data3="estdeliverydate="+self.date+"&ordercode="+saleorder_No+"&shipnotes=&count=1&modelmodule_1=5.CP.3630-LoRa%E6%A8%A1%E5%9D%97&breserve_1="+self.CustomerSys_product_code+"&unit_1=%E5%8F%B0&totalnum_1=&productnum_1="+str(self.saleCount)+"&yquantity_1=0&productId_1="+detailId+"&singnum_1="+str(self.saleCount)
        #模块名称含有中文/单位台，先utf8编码再转成字符串
        result3 = self.session.post(self.customersys_host+url1, data=request_data3, headers=self.shipConfirmSave_header,verify=False,cookies=cookies)
        self.assertEqual(json.loads(result3.text)['msg'], "succ", msg="接口请求失败")
        #self.assertTrue(json.loads(result3.text)['success'], msg="接口请求失败")  #json.loads(result1.text)['success']获取到True为布尔值
        self.mylog.info(result3.text)  #str

    def test04(self):
        self.mylog.info('这是第四个测试用例:erp销售单保存组装生产加工单')
        self.mylog.info('——先获取po_order_detail里面的单号信息——')
        sql = "SELECT TOP 1 * FROM po_order_detail WHERE customercode='{0}' ORDER BY poid DESC ".format(self.CustomerSys_customercode)
        global po_order_ordercode,po_order_id
        po_order_ordercode =self.SqlServer.query_one_data(sql)[2]
        po_order_id = self.SqlServer.query_one_data(sql)[1]
        #print(type(po_order_id))
        if po_order_ordercode==saleorder_No:
            url4 = "/sc/scorder/save"
            request_data4 = {
                    "scOrderEntity": {
                    "id": "",
                    "scDate": self.d_date,
                    "scCode": self.scorder_No,
                    "deptCode": 41,
                    "deptName": "生产车间1",
                    "leadingCode": 84,
                    "personname": "chenhuanfu",
                    "preStartTime": self.d_date,
                    "preFinishTime": self.d_date,
                    "makerCode": 84,
                    "makerName": "chenhuanfu",
                    "auditState": 0,
                    "deliveryTime": self.d_date,
                    "deliveryMark": "北大青鸟（JB-TB-JBF-11S）,数据上四信平台，再推送到智赣119平台",
                    "artisan": "谢海海",
                    "internaluser": "管理员",
                    "ordertime": self.d_date,
                    "customerCode": self.CustomerSys_customercode,
                    "baseQuantity": 0,
                    "company": 3,
                    "partRemark": "",
                    "packRemark": "",
                    "sendArea": "国内",
                    "workShop": "组装车间",
                    "productCompany": "71",
                    "sourceOrderCode": saleorder_No,
                    "sourceType": 0,
                    "orderCode": po_order_id,
                    "billStatus": 1,
                    "auditCode": 84
                },
                    "scOrderProductEntities": [
                                                {
                                                    "itemid": 1,
                                                    "stockCode": self.CustomerSys_product_code,
                                                    "detailId": po_order_id,
                                                    "productName": self.CustomerSys_product_name,
                                                    "quantity": 200,
                                                    "bomId": 12944,
                                                    "bomVersion": techCode,
                                                    "stockModel": "产成品F8L10A-L51",
                                                    "accessories": "标配+北大青鸟 （JB-TB-JBF-11S)",
                                                    "packages": "单独",
                                                    "warrantycard": self.saleCount,
                                                    "hardwarecustom": "无",
                                                    "softwarecustom": "无",
                                                    "customparts": "无",
                                                    "customsigns": "无",
                                                    "technicalfile": sale_tech_confirm_id
                                                }
                                                 ],
                    "scOrderDetailEntityList": [
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "needQuantity": "200.000",
                                                        "status": 4,
                                                        "category": "20整机配件-选配",
                                                        "partName": "",
                                                        "subBomId": "",
                                                        "subParentId": "",
                                                        "stockCode": "3701020000-76S",
                                                        "id": 20087,
                                                        "replaceStocks": "",
                                                        "subVersion": "",
                                                        "productName": "1.WK.0033-1.WK.0033-天线帽",
                                                        "storeName": "",
                                                        "allStockCount": 1490,
                                                        "stockCount": 1490,
                                                        "stockModel": "天线帽",
                                                        "sourceNo": "",
                                                        "buyWay": 1320,
                                                        "stockEnableCount": -47232,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 180,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 0,
                                                        "produceWaitout": 48902,
                                                        "groupName": "370102 孔塞",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3701020000-76S",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 0,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "10主机-选配",
                                                        "partName": "",
                                                        "subBomId": 177640,
                                                        "subParentId": 0,
                                                        "stockCode": "2005020014-7GS",
                                                        "id": 20088,
                                                        "replaceStocks": "2005020014-7GS",
                                                        "subVersion": "",
                                                        "productName": "1.EZ.0391-直插排针",
                                                        "storeName": "",
                                                        "allStockCount": 7734,
                                                        "stockCount": 7734,
                                                        "stockModel": "4PI单排直插插针,间距2.54MM,针长11.6mm",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 7166,
                                                        "roundingOut": 0,
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 350,
                                                        "produceWaitout": 568,
                                                        "groupName": "200502 插件单排排针",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "2005020014-7GS",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 3,
                                                        "outStoreId": "2",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "10主机-选配",
                                                        "partName": "",
                                                        "subBomId": 177641,
                                                        "subParentId": 0,
                                                        "stockCode": "3001070034-7AR",
                                                        "id": 20089,
                                                        "replaceStocks": "3001070034-7AR",
                                                        "subVersion": "",
                                                        "productName": "2.YZ.0808-半成品",
                                                        "storeName": "",
                                                        "allStockCount": 0,
                                                        "stockCount": 0,
                                                        "stockModel": "半成品F8L10A-H V1.1(样机)",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": -365,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 600,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 0,
                                                        "produceWaitout": 365,
                                                        "groupName": "300107 LoRa模组和终端系列半成品",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3001070034-7AR",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 0,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "20整机配件",
                                                        "partName": "",
                                                        "subBomId": 177642,
                                                        "subParentId": 0,
                                                        "stockCode": "2003020010-7EH",
                                                        "id": 20090,
                                                        "replaceStocks": "2003020010-7EH",
                                                        "subVersion": "",
                                                        "productName": "1.EZ.0194-直插插座",
                                                        "storeName": "",
                                                        "allStockCount": 6434,
                                                        "stockCount": 6434,
                                                        "stockModel": "5PIN单排直插插座,间距2.54MM",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 4855,
                                                        "roundingOut": 0,
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 350,
                                                        "produceWaitout": 1579,
                                                        "groupName": "200302 插件WAFER",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "2003020010-7EH",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 3,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "20整机配件-选配",
                                                        "partName": "",
                                                        "subBomId": 177643,
                                                        "subParentId": 0,
                                                        "stockCode": "3903010233-7BP",
                                                        "id": 20091,
                                                        "replaceStocks": "3903010235-7BP,3903010233-74V,3903010235-74V,3903010235-74V",
                                                        "subVersion": "",
                                                        "productName": "4.BP.1224-标牌",
                                                        "storeName": "",
                                                        "allStockCount": 49824,
                                                        "stockCount": 63142.955,
                                                        "stockModel": "F8L10A-H标牌(海外版:868/915MHz),耐高温PI材质,11.4*12.4mm",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 62709.953,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 350,
                                                        "produceWaitout": 433,
                                                        "groupName": "390301 标准标牌",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3903010233-7BP",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "400.000",
                                                        "status": 2,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "30 包材",
                                                        "partName": "",
                                                        "subBomId": 141504,
                                                        "subParentId": 2446,
                                                        "stockCode": "3901010001-74M",
                                                        "id": 20093,
                                                        "replaceStocks": "3901010001-73L",
                                                        "subVersion": "",
                                                        "productName": "4.BC.0002-4.BC.0002-4.BC.0002-纸盒",
                                                        "storeName": "",
                                                        "allStockCount": 0,
                                                        "stockCount": 11907.2,
                                                        "stockModel": "标准MODEM/单口路由纸盒（28.7*18.7*7.8）",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": -29061.395,
                                                        "roundingOut": 0,
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 500,
                                                        "pleaseUnexecute": 350,
                                                        "produceWaitout": 41468.594,
                                                        "groupName": "390101 纸盒",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "2.00000000",
                                                        "productCode": "3901010001-74M",
                                                        "planQuantity": "400.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 2,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "30 包材",
                                                        "partName": "",
                                                        "subBomId": 141505,
                                                        "subParentId": 2446,
                                                        "stockCode": "3902010000-7D2",
                                                        "id": 20094,
                                                        "replaceStocks": "3902010000-7CT,3902010000-73T",
                                                        "subVersion": "",
                                                        "productName": "4.BC.0004-4.BC.0004-珍珠棉",
                                                        "storeName": "",
                                                        "allStockCount": 24.93,
                                                        "stockCount": 25678.063,
                                                        "stockModel": "标准MODEM/单口路由珍珠棉（26.5*17.5*6.0）",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 24250.137,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 2350,
                                                        "produceWaitout": 1427.926,
                                                        "groupName": "390201 珍珠棉",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3902010000-7D2",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 1,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "30包材-选配",
                                                        "partName": "",
                                                        "subBomId": 177645,
                                                        "subParentId": 0,
                                                        "stockCode": "3301020027-70Z",
                                                        "id": 20095,
                                                        "replaceStocks": "3301020027-76S,3301020027-70Z",
                                                        "subVersion": "",
                                                        "productName": "3.WY.0165-LoRa吸盘单极子天线",
                                                        "storeName": "",
                                                        "allStockCount": 4377,
                                                        "stockCount": 4377,
                                                        "stockModel": "1m长,频率410-510MHz,接头SMA-J,线材 RG174,尺寸 143mm",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 4221,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 0,
                                                        "produceWaitout": 156,
                                                        "groupName": "330102 吸盘天线",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3301020027-70Z",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "200.000",
                                                        "status": 1,
                                                        "outStoreId": "",
                                                        "remark": "",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "30包材-选配",
                                                        "partName": "",
                                                        "subBomId": 177646,
                                                        "subParentId": 0,
                                                        "stockCode": "3301020028-70Z",
                                                        "id": 20096,
                                                        "replaceStocks": "3301020028-76L,3301020028-76S,3301020028-70Z",
                                                        "subVersion": "",
                                                        "productName": "3.WY.0166-蜂窝吸盘单极子天线",
                                                        "storeName": "",
                                                        "allStockCount": 4389,
                                                        "stockCount": 4389,
                                                        "stockModel": "1m长,频率848-935MHz,接头SMA-J,线材 RG174,尺寸 90mm",
                                                        "remarks": "",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 4018,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 0,
                                                        "produceWaitout": 371,
                                                        "groupName": "330102 吸盘天线",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "1.00000000",
                                                        "productCode": "3301020028-70Z",
                                                        "planQuantity": "200.000"
                                                    },
                                                    {
                                                        "techConfirmId": sale_tech_confirm_id,
                                                        "supplierCode": "",
                                                        "needQuantity": "0.200",
                                                        "status": 1,
                                                        "outStoreId": "",
                                                        "remark": "根据需要选配",
                                                        "bitNo": "",
                                                        "bitNoS": "",
                                                        "weld": "",
                                                        "category": "30包材-选配",
                                                        "partName": "",
                                                        "subBomId": 177647,
                                                        "subParentId": 0,
                                                        "stockCode": "3902070006-71H",
                                                        "id": 20097,
                                                        "replaceStocks": "3902070006-71H",
                                                        "subVersion": "",
                                                        "productName": "4.BC.0165-4.BC.0165-载带",
                                                        "storeName": "",
                                                        "allStockCount": 5009.175,
                                                        "stockCount": 5009.175,
                                                        "stockModel": "F8L10A载带,φ330mm,宽度24.5mm,每格15*15mm,1000PCS/卷(临时)",
                                                        "remarks": "根据需要选配",
                                                        "sourceNo": "",
                                                        "buyWay": 0,
                                                        "stockEnableCount": 5008.119,
                                                        "roundingOut": "",
                                                        "purchaseWaitin": 0,
                                                        "productWaitIn": 0,
                                                        "buyWaitin": 0,
                                                        "pleaseUnexecute": 0,
                                                        "produceWaitout": 1.056,
                                                        "groupName": "390207 其他（打包带、拉伸膜、栈板、干燥剂）",
                                                        "supplierName": "",
                                                        "techCode": techCode,
                                                        "bomId": 12944,
                                                        "storeCode": "",
                                                        "stillNeedQuantity": "",
                                                        "baseQuantity": "0.00100000",
                                                        "productCode": "3902070006-71H",
                                                        "planQuantity": "0.200"
                                                        }
                                                    ]
                }
            cookies = self.get_cookie.get_cookie(self.session,self.erp_host,self.erp_login_header,"chenhuanfu", "chenhuanfu")
            result4 = self.session.post(self.erp_host+url4, data=json.dumps(request_data4),headers=self.erp_header,cookies=cookies,verify=False)
            self.assertEqual(result4.json()["msg"], "success", msg="接口请求失败")
            self.mylog.info(result4.text)
        else:
            self.mylog.info("未找到销售单")

    def test05(self):
        self.mylog.info('这是第五个测试用例:组装生产单审核')
        self.mylog.info('——先查询获取生产单id——')
        sql = "SELECT a.id FROM sc_order a  WHERE sc_code='{0}' ".format(self.scorder_No)
        #print(sql)
        sc_order_id = self.SqlServer.query_one_data(sql)[0]
        cookies = self.get_cookie.get_cookie(self.session, self.erp_host, self.erp_login_header, "chenhuanfu","chenhuanfu")
        url5 = "/sc/scorder/audit"
        request_data5 = {
                "id": sc_order_id,
                "scCode": self.scorder_No,
                "scDate": self.date,
                "sourceOrderCode": po_order_ordercode,
                "deptCode": 41,
                "workShop": "组装车间",
                "leadingCode": 84,
                "preStartTime": self.d_date,
                "preFinishTime": self.d_date,
                "auditPreStartTime": self.d_date,
                "auditPreFinishTime": self.d_date,
                "auditState": "1",
                "prodStatus": "0",
                "auditDate": None,
                "auditCode": 84,
                "orderCode": po_order_id,
                "makerCode": 84,
                "totalAmount": None,
                "remark": None,
                "printTimes": 0,
                "updateTime":self.date_time,
                "company": 3,
                "productCompany": 71,
                "year": 2021,
                "deleteStatus": 0,
                "billStatus": "1",
                "deliveryTime": self.d_date,
                "customerCode": self.CustomerSys_customercode ,
                "artisan": "谢海海",
                "deliveryMark": "北大青鸟（JB-TB-JBF-11S）,数据上四信平台，再推送到智赣119平台",
                "partRemark": "",
                "packRemark": "",
                "auditMark": "",
                "owner": "未审核",
                "sendArea": "国内",
                "stockCode": "5001070007-L51",
                "stockName": "5.CP.3630-LoRa模块",
                "stockModel": "产成品F8L10A-L51",
                "unitName": "PCS",
                "companyName": "厦门四信通信科技有限公司",
                "productCompanyName": None,
                "quantity": 200,
                "performedQuantity": 0,
                "planQuantity": 0,
                "planingQuantity": 0,
                "packages": "单独",
                "email": None,
                "ordertime": self.d_date,
                "internaluser": "管理员",
                "internalUserId": None,
                "sourceType": 0,
                "handleState": 0,
                "makerName": "chenhuanfu",
                "auditName": "chenhuanfu",
                "deptName": "生产车间1",
                "deliveryQuantity": None,
                "inStoreQuantity": 0,
                "personname": "陈焕富",
                "softversion": None,
                "accessories": None,
                "warrantycard": None,
                "hardwarecustom": None,
                "softwarecustom": None,
                "customparts": None,
                "customsigns": None,
                "technicalnotes": None,
                "techConfirmId": None,
                "techCode": techCode,
                "preStartTimeExport": None,
                "preFinishTimeExport": None,
                "deliveryTimeExport": None,
                "ordertimeExport": None,
                "scDateExport": None,
                "auditStateExport": None,
                "bomVersion": "V1.0.0.1",
                "warehousePersonNames": None,
                "unDownLoad": 0,
                "execdownload": 0,
                "scCodes": None,
                "bomId": None,
                "companyStockCount": None,
                "allStockCount": None,
                "storeStockCount": None,
                "createTime": self.date
            }
        before_productwaitin_quantity = self.get_st_stock_quantity.query_quantity("product_wait_in",self.CustomerSys_product_code, 3)
        result5 = self.session.post(self.erp_host + url5, data=json.dumps(request_data5), headers=self.erp_header,cookies=cookies, verify=False)
        self.assertEqual(result5.json()["msg"], "success", msg="接口请求失败")
        self.mylog.info(result5.text)
        after_productwaitin_quantity = self.get_st_stock_quantity.query_quantity("product_wait_in",self.CustomerSys_product_code, 3)
        self.get_st_stock_quantity.judege_after_before("product_wait_in", before_productwaitin_quantity, after_productwaitin_quantity ,self.saleCount, "入库待入量")

    def test06(self):
        self.mylog.info('这是第六个测试用例:客服系统送货单确认')
        login_requert_data = {"account": "admin",
                              "userPwd": "xmsx123"}
        cookies = self.get_cookie.customer_sys_get_cookies(self.session, self.customersys_host, login_requert_data,self.customersys_login_header)
        self.mylog.info('——先查询id——')
        url6_1 = "/customer/contract/listPage.do"
        request_data6_1 = {"usertype":9,
                           "pagetype":1,
                           "username":"管理员",
                           "ordercode":saleorder_No
                           }
        result6_1 = self.session.post(self.customersys_host + url6_1, data=request_data6_1,headers=self.shipConfirmSave_header, verify=False, cookies=cookies)
        #self.mylog.info(json.dumps(xmltodict.parse(result6_1.text),indent=1))  #查询结果xml转成json格式。"div"."tbody"."tr"."@ondblclick"
        result6_1_json=json.dumps(xmltodict.parse(result6_1.text),indent=1)
        print(type(result6_1_json))
        #print(eval(eval(eval(result6_1_json["div"])["tbody"])["tr"])["@ondblclick"])
        id = re.findall('\(.+\)', eval(eval(eval(json.loads(result6_1_json)["div"])["tbody"])["tr"])["@ondblclick"])
        print(id)
        url6 = "/customer/make/deliveryConfirm.do"
        request_data6 ={"id":"07bc89515a4a485e81aa47996d173a3f"}
        result6 = self.session.post(self.customersys_host + url6, data=request_data6, headers=self.shipConfirmSave_header, verify=False, cookies=cookies)
        self.assertEqual(json.loads(result6.text)['msg'], "succ", msg="接口请求失败")
        # self.assertTrue(json.loads(result3.text)['success'], msg="接口请求失败")  #json.loads(result1.text)['success']获取到True为布尔值
        self.mylog.info(result6.text)  # str

    def test07(self):
        self.mylog.info('这是第七个测试用例:客服系统送货单保存')
        login_requert_data = {"account": "admin",
                              "userPwd": "xmsx123"}
        cookies = self.get_cookie.customer_sys_get_cookies(self.session, self.customersys_host, login_requert_data,self.customersys_login_header)
        url7 = "/customer/make/addDeliverySave.do"
        request_data7 ={ 'deliverytime':self.date,
                        'templetname':'1X03 1X02 1X04',
                        'processnum_1':self.scorder_No,
                        'deliveryid':'',
                        'productid_1':'e95f2d37ca8d424da9f11ab05b6c1780',
                        'deliverycode_1':'5001070007-L51',
                        'modelmodule_1':'5.CP.3630-LoRa模块',
                        'materialnum_1':'台',
                        'quantity_1':200,
                        'parts':'天线',
                        'parts1':'电源',
                        'parts2':'网线',
                        'parts3':'端子三芯线',
                        'parts4':'GPS天线',
                        'parts5':'串口线',
                        'parts6':'WIFI天线',
                        'parts7':'',
                        'parts8':'',
                        'partsunit':'根',
                        'partsunit1':'个',
                        'partsunit2':'根',
                        'partsunit3':'根',
                        'partsunit4':'根',
                        'partsunit5':'根',
                        'partsunit6':'根',
                        'partsunit7':'',
                        'partsunit8':'',
                        'partsnum':200,
                        'partsnum1':200,
                        'partsnum2':200,
                        'partsnum3':200,
                        'partsnum4':200,
                        'partsnum5':200,
                        'partsnum6':200,
                        'partsnum7':'',
                        'partsnum8':'',
                        'partsmark':'',
                        'ordercode':'FF55320211115164204',
                        'productid':'',
                        'count':2,
                        'singleid':'07bc89515a4a485e81aa47996d173a3f',
                        'cargoid':'6433d9f1130142c5a3de32b2c0827a3b'
                        }

        result7 = self.session.post(self.customersys_host + url7, data=request_data7, headers=self.shipConfirmSave_header, verify=False, cookies=cookies)
        self.assertEqual(json.loads(result7.text)['msg'], "succ", msg="接口请求失败")
        # self.assertTrue(json.loads(result3.text)['success'], msg="接口请求失败")  #json.loads(result1.text)['success']获取到True为布尔值
        self.mylog.info(result7.text)  # str

    @classmethod
    def tearDownClass(cls):
        cls.mylog.info("客服销售单到erp生产流程结束\n")

if __name__ == '__main__':
    unittest.main()
